---
title: "Daghestanian stops"
subtitle: "VOT, CD and other stories"
author: "M. Daniel, S. Grawunder, G. Moroz, V. Zhigulskaya"
date: "2017/10/03"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = FALSE,
                      message=FALSE,
                      warning= FALSE,
                      fig.width=10.4,
                      fig.height=7)
```

class: inverse, center, middle

# Motivation

---

# Introduction

<audio controls>
  <source src="https://www.w3schools.com/html/horse.ogg" type="audio/ogg">
</audio>

---
class: inverse, center, middle

# Data

---
# Villages

```{r}
library(tidyverse)
library(lingtypology)
library(ggjoy)
df <- read_csv("speakers.csv")
df %>% 
  distinct(Language, Location, lon, lat, color) -> 
  df_u
map.feature(df_u$Language,
            features = df_u$Language,
            tile = "Esri.OceanBasemap",
            label = df_u$Location,
            label.hide = FALSE,
            label.fsize = 19,
            longitude = df_u$lon,
            latitude = df_u$lat,
            minimap = TRUE,
            minimap.position = "topleft",
            color = df_u$color)
```
---
# Speakers by village
```{r}
df %>% 
  count(Location) %>% 
  full_join(df) %>% 
  mutate(`(all)` = n) %>% 
  count(Location, `(all)`, Gender) %>% 
  spread(Gender, nn) %>% 
  mutate(f = ifelse(is.na(f), 0, f)) %>% 
  gather(Gender, n, `(all)`:m) ->
  annotation

df %>% 
  count(Location, Gender) %>% 
  full_join(df) %>% 
  filter(!is.na(Age)) ->
  df_plot

df_plot[,-2] %>% 
  mutate(Gender = "(all)") ->
  df_plot2

df_plot %>% 
  ggplot(aes(x = Age, y = Location)) +
  geom_joy(aes(fill = Gender), alpha = 0.6, show.legend = FALSE) +
  geom_joy(data = df_plot2, aes(fill = Gender), alpha = 0.6, show.legend = FALSE) +
  geom_text(data = annotation, aes(label = n, x = 2030), size = 8)+
  theme_bw()+
  facet_grid(~Gender)+
  theme(text = element_text(size=20))+
  labs(y = "", x = "",
       title = "Year of birth")+
  scale_x_continuous(breaks = 1:4*30+1890)
```
---
# Speakers by language
```{r}
df %>% 
  count(Language) %>% 
  full_join(df) %>% 
  mutate(`(all)` = n) %>% 
  count(Language, `(all)`, Gender) %>% 
  spread(Gender, nn) %>% 
  mutate(f = ifelse(is.na(f), 0, f)) %>% 
  gather(Gender, n, `(all)`:m) ->
  annotation

df %>% 
  count(Language, Gender) %>% 
  full_join(df) %>% 
  filter(!is.na(Age)) ->
  df_plot

df_plot[,-2] %>% 
  mutate(Gender = "(all)") ->
  df_plot2

df_plot %>% 
  ggplot(aes(x = Age, y = Language)) +
  geom_joy(aes(fill = Gender), alpha = 0.6, show.legend = FALSE) +
  geom_joy(data = df_plot2, aes(fill = Gender), alpha = 0.6, show.legend = FALSE) +
  geom_text(data = annotation, aes(label = n, x = 2030), size = 8)+
  theme_bw()+
  facet_grid(~Gender)+
  theme(text = element_text(size=20))+
  labs(y = "", x = "",
       title = "Year of birth")+
  scale_x_continuous(breaks = 1:4*30+1890)
```

---
# Stops and affricates

---
# Lists of words

---
class: inverse, center, middle

# Annotation

---
class: inverse, center, middle

# Results

---

class: center, middle

# Thanks!

Slides created with the following R packages:

[**xaringan**](https://github.com/yihui/xaringan)

[**ggplot2**](http://ggplot2.org)

[**lingtypology**](https://ropensci.github.io/lingtypology/)

[**ggjoy**](https://CRAN.R-project.org/package=ggjoy)
